/**
 * P3-LU-SPATIAL-TEST-DB-01 — provisions the disposable PostGIS test database.
 *
 * The spatial proofs in `packages/spatial-provider-postgis/tests/` DELETE and INSERT rows.
 * They must therefore own a database of their own. Before this script existed, nothing in the
 * repository created one: `riskguard_test` could not come into being from a clean checkout, so
 * the spatial proofs were unreproducible by construction and only ever ran on a machine where
 * somebody had built the database by hand.
 *
 * What this creates is the MINIMUM the tests touch — three tables — not a clone of the
 * production database. Copying `miljobeslut` would drag real geodata into a database that tests
 * are allowed to delete from.
 *
 *   npx tsx scripts/db/provision-spatial-test-db.ts
 *   npx tsx scripts/db/provision-spatial-test-db.ts --drop   (recreate from scratch)
 *
 * Idempotent: re-running is safe and makes no changes on an already-provisioned database.
 *
 * ⚠️ It refuses to touch anything that is not the configured test database. The guard is on the
 * resolved database NAME, checked against the app connection, because a provisioning script
 * that can write to production is a worse problem than an unprovisioned test database.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { Client } from 'pg';

/** Tables the spatial proofs actually read and write. Nothing else is created. */
const REQUIRED_TABLES = [
  {
    name: 'sgu_well',
    // Production types this MULTIPOINT, but SpatialProviderPostGIS.test.ts inserts a bare
    // ST_MakePoint. Typing it strictly here would fail the very test this database exists to
    // run, so the geometry type is left open while the SRID — the part that carries spatial
    // meaning — stays constrained. The divergence is real and worth resolving upstream; see
    // the unit note in docs/architecture.
    ddl: `
      CREATE TABLE IF NOT EXISTS env.sgu_well (
        id   integer PRIMARY KEY,
        geom geometry(Geometry, 3006)
      )`,
  },
  {
    name: 'ebh_potentiellt_fororenade_omraden',
    ddl: `
      CREATE TABLE IF NOT EXISTS env.ebh_potentiellt_fororenade_omraden (
        fid  integer PRIMARY KEY,
        geom geometry(MultiPoint, 3006)
      )`,
  },
  {
    // RC6-C: source-faithful NVR materialization. Matches production's
    // actual raw shape. Never queried by name from application/test code --
    // see prisma/spatial/006_protected_area_physical_boundary.sql.
    name: 'protected_area_nvr_raw',
    ddl: `
      CREATE TABLE IF NOT EXISTS env.protected_area_nvr_raw (
        ogc_fid   integer PRIMARY KEY,
        nvrid     varchar,
        namn      varchar,
        skyddstyp varchar,
        geom      geometry(MultiPolygon, 3006)
      )`,
  },
  {
    // RC6-C: canonical normalized read model. The only protected-area
    // surface consumers may query.
    name: 'protected_area',
    ddl: `
      CREATE TABLE IF NOT EXISTS env.protected_area (
        nvr_id          text PRIMARY KEY,
        name            text,
        protection_type text,
        decision_status text,
        source_dataset  text,
        geom            geometry(MultiPolygon, 3006),
        area_ha         double precision GENERATED ALWAYS AS (ST_Area(geom) / 10000.0) STORED
      )`,
  },
] as const;

/**
 * The E2E chain proof seeds a property before it can assess one, so it needs `core` as well.
 * `normalize_designation` is called inline in its INSERT, which is why the function has to
 * exist rather than just the table.
 */
const CORE_OBJECTS = [
  {
    name: 'core.property_unit',
    ddl: `
      CREATE TABLE IF NOT EXISTS core.property_unit (
        id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_key        text UNIQUE,
        designation       text,
        designation_norm  text,
        municipality_code text,
        municipality_name text,
        county_code       text,
        source_dataset    text,
        source_updated_at timestamptz,
        raw_properties    jsonb,
        geom              geometry(MultiPolygon, 3006)
      )`,
  },
  {
    name: 'core.normalize_designation(text)',
    // Copied verbatim from production so the test database normalises designations identically.
    // A divergent implementation here would make designation lookups pass locally and fail in
    // production, or the reverse.
    ddl: `
      CREATE OR REPLACE FUNCTION core.normalize_designation(input text)
      RETURNS text LANGUAGE plpgsql IMMUTABLE AS $fn$
      BEGIN
        RETURN UPPER(REGEXP_REPLACE(UNACCENT(input), '[^a-zA-Z0-9:]', '', 'g'));
      END;
      $fn$`,
  },
] as const;

const INDEXES = [
  'CREATE INDEX IF NOT EXISTS sgu_well_geom_idx ON env.sgu_well USING GIST (geom)',
  'CREATE INDEX IF NOT EXISTS ebh_geom_idx ON env.ebh_potentiellt_fororenade_omraden USING GIST (geom)',
  'CREATE INDEX IF NOT EXISTS protected_area_geom_idx ON env.protected_area USING GIST (geom)',
  'CREATE INDEX IF NOT EXISTS protected_area_nvr_raw_geom_idx ON env.protected_area_nvr_raw USING GIST (geom)',
  'CREATE INDEX IF NOT EXISTS property_unit_geom_idx ON core.property_unit USING GIST (geom)',
];

/**
 * Every extension the migrations declare, plus `unaccent` for core.normalize_designation and
 * `pg_trgm` for the trigram index on core.property_unit.designation_norm.
 *
 * All of these must be created by the admin role BEFORE `migrate deploy` runs. The migrations
 * say `CREATE EXTENSION IF NOT EXISTS`, but they execute as the test role, which is not
 * superuser — so the statement is a permission error unless the extension already exists, in
 * which case it is a harmless no-op.
 *
 * GIS_TEST_DB_EXTENSION_OWNERSHIP-01: extensions are a provisioning concern, never a per-test
 * one. `pg_trgm` and `unaccent` happen to be trusted in PostgreSQL 16 and could technically be
 * created by the test role, but splitting the lifecycle on whether Postgres marks an extension
 * trusted would leave two different rules for the same kind of object. All of them are
 * provisioned here; tests/setup/seedGisStubs.ts only ever verifies that they are present.
 */
const EXTENSIONS = ['postgis', 'postgis_raster', 'vector', 'unaccent', 'pg_trgm'];

function readEnvFile(path: string): Record<string, string> {
  try {
    return Object.fromEntries(
      readFileSync(resolve(path), 'utf8')
        .split(/\r?\n/)
        .filter((line) => /^[A-Z_]+=/.test(line))
        .map((line) => {
          const i = line.indexOf('=');
          return [line.slice(0, i), line.slice(i + 1).replace(/^["']|["']$/g, '')];
        }),
    );
  } catch {
    return {};
  }
}

function fail(message: string): never {
  console.error(`\n❌ ${message}\n`);
  process.exit(1);
}

async function main(): Promise<void> {
  const testEnv = readEnvFile('.env.test');
  const appEnv = readEnvFile('.env');

  const targetUrl = testEnv.TEST_DATABASE_URL ?? testEnv.DATABASE_URL;
  if (!targetUrl) {
    fail(
      '.env.test defines neither TEST_DATABASE_URL nor DATABASE_URL. That file is the canonical ' +
        'contract for the local test database — provisioning must not invent a connection.',
    );
  }

  // The admin connection only has to be able to CREATE ROLE / CREATE DATABASE. It is never
  // written to.
  const adminUrl = process.env.ADMIN_DATABASE_URL ?? appEnv.DATABASE_URL;
  if (!adminUrl) {
    fail('No admin connection. Set ADMIN_DATABASE_URL, or DATABASE_URL in .env.');
  }

  const target = new URL(targetUrl);
  const admin = new URL(adminUrl);
  const targetDb = target.pathname.replace(/^\//, '');
  const adminDb = admin.pathname.replace(/^\//, '');
  const targetRole = decodeURIComponent(target.username);

  // ---------------------------------------------------------------- safety guard
  if (!targetDb) fail(`Could not read a database name from TEST_DATABASE_URL.`);
  if (targetDb === adminDb) {
    fail(
      `REFUSING TO PROVISION: the test database and the application database are both ` +
        `'${targetDb}'. The spatial proofs DELETE rows; pointing them at the application ` +
        `database would let a test run destroy real geodata.`,
    );
  }
  if (!/test/i.test(targetDb)) {
    fail(
      `REFUSING TO PROVISION: '${targetDb}' does not look like a test database. This script ` +
        `creates a database that tests are permitted to delete from, so the name must say so.`,
    );
  }

  const drop = process.argv.includes('--drop');
  console.log(`\n🗄️  target   : ${targetDb} (role '${targetRole}')`);
  console.log(`🔑 admin via: ${adminDb}`);
  if (drop) console.log('⚠️  --drop: the target database will be recreated from scratch');

  // ------------------------------------------------------------ role + database
  const adminClient = new Client({ connectionString: adminUrl });
  await adminClient.connect();
  try {
    const role = await adminClient.query('SELECT 1 FROM pg_roles WHERE rolname = $1', [targetRole]);
    if (role.rowCount === 0) {
      // Password comes from the connection string in .env.test — the single contract. Quoting
      // the literal rather than interpolating it into DDL text keeps it out of any log.
      await adminClient.query(
        `CREATE ROLE ${JSON.stringify(targetRole).replace(/"/g, '"')} LOGIN PASSWORD $1`.replace(
          '$1',
          `'${decodeURIComponent(target.password).replace(/'/g, "''")}'`,
        ),
      );
      console.log(`   ✅ role '${targetRole}' created`);
    } else {
      console.log(`   • role '${targetRole}' already exists`);
    }

    if (drop) {
      await adminClient.query(`DROP DATABASE IF EXISTS "${targetDb}"`);
      console.log(`   ✅ database '${targetDb}' dropped`);
    }

    const db = await adminClient.query('SELECT 1 FROM pg_database WHERE datname = $1', [targetDb]);
    if (db.rowCount === 0) {
      await adminClient.query(`CREATE DATABASE "${targetDb}" OWNER "${targetRole}"`);
      console.log(`   ✅ database '${targetDb}' created`);
    } else {
      console.log(`   • database '${targetDb}' already exists`);
    }
  } finally {
    await adminClient.end();
  }

  // --------------------------------------------------------------- extensions
  // Must precede the migrations: they declare `CREATE EXTENSION IF NOT EXISTS postgis`, but run
  // as the test role, which is not superuser. Creating the extensions here as admin makes those
  // statements no-ops instead of permission errors.
  const extClient = new Client({
    connectionString: (() => {
      const u = new URL(adminUrl);
      u.pathname = `/${targetDb}`;
      return u.toString();
    })(),
  });
  await extClient.connect();
  try {
    for (const extension of EXTENSIONS) {
      await extClient.query(`CREATE EXTENSION IF NOT EXISTS ${extension}`);
    }
    const v = await extClient.query('SELECT postgis_version() AS v');
    console.log(`   ✅ extensions: postgis ${String(v.rows[0].v).split(' ')[0]}, ${EXTENSIONS.slice(1).join(', ')}`);
  } finally {
    await extClient.end();
  }

  // ------------------------------------------------------ prisma migrations
  // Ordering is load-bearing. The migrations own the schemas, the application tables and the
  // PostGIS extensions, and one of them DROPs the spatial stub tables. Creating the spatial
  // objects before this point means `migrate deploy` fails on tables it does not own, or drops
  // what was just built. Migrations first, spatial objects after.
  //
  // Four objects the spatial proofs need are in NO migration — core.property_unit,
  // core.normalize_designation, env.ebh_potentiellt_fororenade_omraden, and env.sgu_well, which
  // a later migration drops. They exist in production but were created outside the migration
  // chain, which is why this script has to supply them and why the gap is worth closing
  // upstream.
  console.log('\n📦 applying prisma migrations (they own schemas and application tables)');
  const { execSync } = await import('node:child_process');
  try {
    execSync('npm run db:test:migrate', { stdio: 'pipe', encoding: 'utf8' });
    console.log('   ✅ migrations applied');
  } catch (error) {
    const output = (error as { stdout?: string; stderr?: string });
    fail(
      'prisma migrate deploy failed:\n' +
        `${(output.stdout ?? '') + (output.stderr ?? '')}`.split('\n').slice(-12).join('\n'),
    );
  }

  // ------------------------------------------------- extension, schema, tables
  // Connected as admin: creating the PostGIS extension needs privileges the test role does not
  // have. Ownership is handed to the test role afterwards.
  const bootstrapUrl = new URL(adminUrl);
  bootstrapUrl.pathname = `/${targetDb}`;
  const dbClient = new Client({ connectionString: bootstrapUrl.toString() });
  await dbClient.connect();
  try {
    await dbClient.query('CREATE SCHEMA IF NOT EXISTS env');
    for (const table of REQUIRED_TABLES) {
      await dbClient.query(table.ddl);
      console.log(`   ✅ env.${table.name}`);
    }

    await dbClient.query('CREATE SCHEMA IF NOT EXISTS core');
    for (const object of CORE_OBJECTS) {
      await dbClient.query(object.ddl);
      console.log(`   ✅ ${object.name}`);
    }

    for (const index of INDEXES) await dbClient.query(index);

    for (const schema of ['env', 'core']) {
      await dbClient.query(`GRANT ALL ON SCHEMA ${schema} TO "${targetRole}"`);
      await dbClient.query(`GRANT ALL ON ALL TABLES IN SCHEMA ${schema} TO "${targetRole}"`);
      await dbClient.query(
        `GRANT ALL ON ALL SEQUENCES IN SCHEMA ${schema} TO "${targetRole}"`,
      );
      await dbClient.query(
        `ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema} GRANT ALL ON TABLES TO "${targetRole}"`,
      );
    }
    console.log(`   ✅ privileges granted to '${targetRole}'`);
  } finally {
    await dbClient.end();
  }

  // -------------------------------------------------------------- verification
  // Connecting as the TEST role, not as admin: the proofs run as that role, so provisioning is
  // only complete if that role can actually write.
  const verify = new Client({ connectionString: targetUrl });
  await verify.connect();
  try {
    for (const table of REQUIRED_TABLES) {
      await verify.query(`SELECT 1 FROM env.${table.name} LIMIT 1`);
    }
    await verify.query(
      'INSERT INTO env.sgu_well (id, geom) VALUES (999999, ST_SetSRID(ST_MakePoint(0,0), 3006)) ' +
        'ON CONFLICT (id) DO NOTHING',
    );
    await verify.query('DELETE FROM env.sgu_well WHERE id = 999999');
    console.log('   ✅ test role can read, insert and delete\n');
    console.log('Provisioned. Run:  npx vitest run packages/spatial-provider-postgis\n');
  } finally {
    await verify.end();
  }
}

main().catch((error) => fail(error instanceof Error ? error.message : String(error)));
