/**
 * P3-LU-SPATIAL-TEST-DB-01 — provisions the disposable PostGIS test database.
 *
 * The spatial proofs in `packages/spatial-provider-postgis/tests/` DELETE and INSERT rows.
 * They must therefore own a database of their own. Before this script existed, nothing in the
 * repository created one: `riskguard_test` could not come into being from a clean checkout, so
 * the spatial proofs were unreproducible by construction and only ever ran on a machine where
 * somebody had built the database by hand.
 *
 * What this creates is the MINIMUM the tests touch — three tables — not a clone of the
 * production database. Copying `miljobeslut` would drag real geodata into a database that tests
 * are allowed to delete from.
 *
 *   npx tsx scripts/db/provision-spatial-test-db.ts
 *   npx tsx scripts/db/provision-spatial-test-db.ts --drop   (recreate from scratch)
 *
 * Idempotent: re-running is safe and makes no changes on an already-provisioned database.
 *
 * ⚠️ It refuses to touch anything that is not the configured test database. The guard is on the
 * resolved database NAME, checked against the app connection, because a provisioning script
 * that can write to production is a worse problem than an unprovisioned test database.
 */

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Client } from 'pg';

import { applyRc6VersionedSpatialDdl, RC6_OWNED_TABLES } from './lib/applyRc6VersionedSpatialDdl';
import { SPATIAL_LAYER_REGISTRY } from '../../packages/spatial-provider-postgis/src/SpatialLayerRegistry';
import {
  assertDisposableGisTestDatabase,
  type AdmittedDisposableGisTestDatabase,
} from '../../tests/setup/disposableGisTestDatabase';

/**
 * Tables the spatial proofs actually read and write, still hand-defined here.
 *
 * RC6-E moved ebh_potentiellt_fororenade_omraden, protected_area_nvr_raw and protected_area
 * out of this list -- they are now created by applyRc6VersionedSpatialDdl() from
 * prisma/spatial/*.sql, the single schema authority for those three, rather than duplicated
 * here as a second hand-written definition that happened to agree.
 *
 * sgu_well remains hand-defined: it is documented, pre-existing schema-ownership debt
 * (production types it MULTIPOINT; typing it strictly here would fail the very test this
 * database exists to run), out of RC6's scope to resolve now.
 */
const REQUIRED_TABLES = [
  {
    name: 'sgu_well',
    ddl: `
      CREATE TABLE IF NOT EXISTS env.sgu_well (
        id   integer PRIMARY KEY,
        geom geometry(Geometry, 3006)
      )`,
  },
] as const;

/**
 * The E2E chain proof seeds a property before it can assess one, so it needs `core` as well.
 * `normalize_designation` is called inline in its INSERT, which is why the function has to
 * exist rather than just the table.
 */
const CORE_OBJECTS = [
  {
    name: 'core.property_unit',
    ddl: `
      CREATE TABLE IF NOT EXISTS core.property_unit (
        id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_key        text UNIQUE,
        designation       text,
        designation_norm  text,
        municipality_code text,
        municipality_name text,
        county_code       text,
        source_dataset    text,
        source_updated_at timestamptz,
        raw_properties    jsonb,
        geom              geometry(MultiPolygon, 3006)
      )`,
  },
  {
    name: 'core.normalize_designation(text)',
    // Copied verbatim from production so the test database normalises designations identically.
    // A divergent implementation here would make designation lookups pass locally and fail in
    // production, or the reverse.
    ddl: `
      CREATE OR REPLACE FUNCTION core.normalize_designation(input text)
      RETURNS text LANGUAGE plpgsql IMMUTABLE AS $fn$
      BEGIN
        RETURN UPPER(REGEXP_REPLACE(UNACCENT(input), '[^a-zA-Z0-9:]', '', 'g'));
      END;
      $fn$`,
  },
] as const;

// RC6-E: no ebh/protected_area/protected_area_nvr_raw entries here -- their GIST indexes are
// created by prisma/spatial/*.sql itself (applyRc6VersionedSpatialDdl), not duplicated here.
const INDEXES = [
  'CREATE INDEX IF NOT EXISTS sgu_well_geom_idx ON env.sgu_well USING GIST (geom)',
  'CREATE INDEX IF NOT EXISTS property_unit_geom_idx ON core.property_unit USING GIST (geom)',
];

/**
 * Every extension the migrations declare, plus `unaccent` for core.normalize_designation and
 * `pg_trgm` for the trigram index on core.property_unit.designation_norm.
 *
 * All of these must be created by the admin role BEFORE `migrate deploy` runs. The migrations
 * say `CREATE EXTENSION IF NOT EXISTS`, but they execute as the test role, which is not
 * superuser — so the statement is a permission error unless the extension already exists, in
 * which case it is a harmless no-op.
 *
 * GIS_TEST_DB_EXTENSION_OWNERSHIP-01: extensions are a provisioning concern, never a per-test
 * one. `pg_trgm` and `unaccent` happen to be trusted in PostgreSQL 16 and could technically be
 * created by the test role, but splitting the lifecycle on whether Postgres marks an extension
 * trusted would leave two different rules for the same kind of object. All of them are
 * provisioned here; tests/setup/seedGisStubs.ts only ever verifies that they are present.
 */
const EXTENSIONS = ['postgis', 'postgis_raster', 'vector', 'unaccent', 'pg_trgm'];

/**
 * SPATIAL-DATASET-RUNTIME-BINDING-V1. `SpatialProviderPostGIS.query()` now verifies each layer's
 * claimed `version_hash` (SpatialLayerRegistry.ts) against a real SUCCESS row in
 * `PostgisImportBatch` for that layer's table, queried on the SAME connection the spatial query
 * itself runs on -- see `packages/spatial-provider-postgis/src/SpatialDatasetRuntimeBinding.ts`.
 * `PostgisImportBatch` is not owned by any Prisma migration (same "created outside the migration
 * chain" category as `REQUIRED_TABLES`/`CORE_OBJECTS` above; its real DDL lives in
 * `tests/setup/seedGisStubs.ts`, table-only, no seed rows), so the spatial proofs need both the
 * table AND matching SUCCESS rows for the layers they actually query (`water`, `ebh`) to exist
 * here, independent of that other, unrelated setup path.
 */
const POSTGIS_IMPORT_BATCH_DDL = `
  CREATE TABLE IF NOT EXISTS "public"."PostgisImportBatch" (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    harvest_batch_id TEXT,
    target_schema TEXT NOT NULL,
    target_table TEXT NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    row_count INTEGER,
    dataset_version TEXT,
    status TEXT NOT NULL DEFAULT 'PLANNED',
    manifest_path TEXT,
    content_bundle_sha256 TEXT NOT NULL DEFAULT '',
    source_runtime_path TEXT,
    ogr2ogr_version TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    import_mode TEXT NOT NULL DEFAULT 'plan'
  )`;

/** Every layer in SpatialLayerRegistry.ts -- not just the ones a given test happens to query
 *  today, since a future test querying any of the other four would otherwise hit the same
 *  missing-binding gap. Hashes are read from the real registry, never duplicated as a literal,
 *  so this can never silently drift from what the runtime binding check actually requires. */
const POSTGIS_IMPORT_BATCH_SEED_LAYERS = Object.keys(SPATIAL_LAYER_REGISTRY) as (keyof typeof SPATIAL_LAYER_REGISTRY)[];

function readEnvFile(path: string): Record<string, string> {
  try {
    return Object.fromEntries(
      readFileSync(resolve(path), 'utf8')
        .split(/\r?\n/)
        .filter((line) => /^[A-Z_]+=/.test(line))
        .map((line) => {
          const i = line.indexOf('=');
          return [line.slice(0, i), line.slice(i + 1).replace(/^["']|["']$/g, '')];
        }),
    );
  } catch {
    return {};
  }
}

function fail(message: string): never {
  console.error(`\n❌ ${message}\n`);
  process.exit(1);
}

/**
 * Admission is deliberately independent of Vitest setup. This script can be invoked directly
 * and performs destructive DDL, so only TEST_DATABASE_URL may select its target.
 */
export function resolveProvisionedSpatialTestDatabaseTarget(
  testEnv: Record<string, string>,
  envTestPresent: boolean,
): AdmittedDisposableGisTestDatabase {
  return assertDisposableGisTestDatabase({
    envTestPresent,
    databaseUrl: testEnv.TEST_DATABASE_URL,
    disposableFlag: testEnv.GIS_TEST_DB_DISPOSABLE,
    declaredDatabaseName: testEnv.GIS_TEST_DB_NAME,
  });
}

async function main(): Promise<void> {
  const testEnvPath = resolve('.env.test');
  const testEnv = readEnvFile(testEnvPath);
  const appEnv = readEnvFile('.env');

  // Must succeed before any Client is constructed or any SQL becomes reachable.
  const admittedTarget = resolveProvisionedSpatialTestDatabaseTarget(testEnv, existsSync(testEnvPath));
  const targetUrl = admittedTarget.databaseUrl;

  // The admin connection only has to be able to CREATE ROLE / CREATE DATABASE. It is never
  // written to.
  const adminUrl = process.env.ADMIN_DATABASE_URL ?? appEnv.DATABASE_URL;
  if (!adminUrl) {
    fail('No admin connection. Set ADMIN_DATABASE_URL, or DATABASE_URL in .env.');
  }

  const target = new URL(targetUrl);
  const admin = new URL(adminUrl);
  const targetDb = admittedTarget.databaseName;
  const adminDb = admin.pathname.replace(/^\//, '');
  const targetRole = decodeURIComponent(target.username);

  // ---------------------------------------------------------------- safety guard
  if (targetDb === adminDb) {
    fail(
      `REFUSING TO PROVISION: the test database and the application database are both ` +
        `'${targetDb}'. The spatial proofs DELETE rows; pointing them at the application ` +
        `database would let a test run destroy real geodata.`,
    );
  }
  const drop = process.argv.includes('--drop');
  console.log(`\n🗄️  target   : ${targetDb} (role '${targetRole}')`);
  console.log(`🔑 admin via: ${adminDb}`);
  if (drop) console.log('⚠️  --drop: the target database will be recreated from scratch');

  // ------------------------------------------------------------ role + database
  const adminClient = new Client({ connectionString: adminUrl });
  await adminClient.connect();
  try {
    const role = await adminClient.query('SELECT 1 FROM pg_roles WHERE rolname = $1', [targetRole]);
    if (role.rowCount === 0) {
      // Password comes from the connection string in .env.test — the single contract. Quoting
      // the literal rather than interpolating it into DDL text keeps it out of any log.
      await adminClient.query(
        `CREATE ROLE ${JSON.stringify(targetRole).replace(/"/g, '"')} LOGIN PASSWORD $1`.replace(
          '$1',
          `'${decodeURIComponent(target.password).replace(/'/g, "''")}'`,
        ),
      );
      console.log(`   ✅ role '${targetRole}' created`);
    } else {
      console.log(`   • role '${targetRole}' already exists`);
    }

    if (drop) {
      await adminClient.query(`DROP DATABASE IF EXISTS "${targetDb}"`);
      console.log(`   ✅ database '${targetDb}' dropped`);
    }

    const db = await adminClient.query('SELECT 1 FROM pg_database WHERE datname = $1', [targetDb]);
    if (db.rowCount === 0) {
      await adminClient.query(`CREATE DATABASE "${targetDb}" OWNER "${targetRole}"`);
      console.log(`   ✅ database '${targetDb}' created`);
    } else {
      console.log(`   • database '${targetDb}' already exists`);
    }
  } finally {
    await adminClient.end();
  }

  // --------------------------------------------------------------- extensions
  // Must precede the migrations: they declare `CREATE EXTENSION IF NOT EXISTS postgis`, but run
  // as the test role, which is not superuser. Creating the extensions here as admin makes those
  // statements no-ops instead of permission errors.
  const extClient = new Client({
    connectionString: (() => {
      const u = new URL(adminUrl);
      u.pathname = `/${targetDb}`;
      return u.toString();
    })(),
  });
  await extClient.connect();
  try {
    for (const extension of EXTENSIONS) {
      await extClient.query(`CREATE EXTENSION IF NOT EXISTS ${extension}`);
    }
    const v = await extClient.query('SELECT postgis_version() AS v');
    console.log(`   ✅ extensions: postgis ${String(v.rows[0].v).split(' ')[0]}, ${EXTENSIONS.slice(1).join(', ')}`);
  } finally {
    await extClient.end();
  }

  // ------------------------------------------------------ prisma migrations
  // Ordering is load-bearing. The migrations own the schemas, the application tables and the
  // PostGIS extensions, and one of them DROPs the spatial stub tables. Creating the spatial
  // objects before this point means `migrate deploy` fails on tables it does not own, or drops
  // what was just built. Migrations first, spatial objects after.
  //
  // Four objects the spatial proofs need are in NO migration — core.property_unit,
  // core.normalize_designation, env.ebh_potentiellt_fororenade_omraden, and env.sgu_well, which
  // a later migration drops. They exist in production but were created outside the migration
  // chain, which is why this script has to supply them and why the gap is worth closing
  // upstream.
  console.log('\n📦 applying prisma migrations (they own schemas and application tables)');
  const { execSync } = await import('node:child_process');
  try {
    execSync('npm run db:test:migrate', { stdio: 'pipe', encoding: 'utf8' });
    console.log('   ✅ migrations applied');
  } catch (error) {
    const output = (error as { stdout?: string; stderr?: string });
    fail(
      'prisma migrate deploy failed:\n' +
        `${(output.stdout ?? '') + (output.stderr ?? '')}`.split('\n').slice(-12).join('\n'),
    );
  }

  // ------------------------------------------------- extension, schema, tables
  // Connected as admin: creating the PostGIS extension needs privileges the test role does not
  // have. Ownership is handed to the test role afterwards.
  const bootstrapUrl = new URL(adminUrl);
  bootstrapUrl.pathname = `/${targetDb}`;
  const dbClient = new Client({ connectionString: bootstrapUrl.toString() });
  await dbClient.connect();
  try {
    await dbClient.query('CREATE SCHEMA IF NOT EXISTS env');

    // RC6-E: the versioned spatial DDL chain is schema authority for these three -- applied
    // from prisma/spatial/*.sql, not hand-duplicated in this file.
    await applyRc6VersionedSpatialDdl(dbClient);
    for (const name of RC6_OWNED_TABLES) console.log(`   ✅ env.${name} (versioned DDL)`);

    for (const table of REQUIRED_TABLES) {
      await dbClient.query(table.ddl);
      console.log(`   ✅ env.${table.name}`);
    }

    await dbClient.query('CREATE SCHEMA IF NOT EXISTS core');
    for (const object of CORE_OBJECTS) {
      await dbClient.query(object.ddl);
      console.log(`   ✅ ${object.name}`);
    }

    await dbClient.query(POSTGIS_IMPORT_BATCH_DDL);
    console.log('   ✅ public.PostgisImportBatch');
    for (const layerName of POSTGIS_IMPORT_BATCH_SEED_LAYERS) {
      const binding = SPATIAL_LAYER_REGISTRY[layerName];
      const [targetSchema, targetTable] = binding.table.split('.');
      const existing = await dbClient.query(
        `SELECT 1 FROM "public"."PostgisImportBatch" WHERE target_schema = $1 AND target_table = $2 AND status = 'SUCCESS'`,
        [targetSchema, targetTable],
      );
      if (existing.rowCount === 0) {
        await dbClient.query(
          `INSERT INTO "public"."PostgisImportBatch"
             (target_schema, target_table, status, content_bundle_sha256, dataset_version, completed_at)
           VALUES ($1, $2, 'SUCCESS', $3, $4, NOW())`,
          [targetSchema, targetTable, binding.version_hash, `provision-spatial-test-db-${layerName}`],
        );
        console.log(`   ✅ PostgisImportBatch seed row for ${binding.table} (${layerName})`);
      } else {
        console.log(`   • PostgisImportBatch SUCCESS row for ${binding.table} already present`);
      }
    }

    for (const index of INDEXES) await dbClient.query(index);

    await dbClient.query(`GRANT ALL ON "public"."PostgisImportBatch" TO "${targetRole}"`);

    for (const schema of ['env', 'core']) {
      await dbClient.query(`GRANT ALL ON SCHEMA ${schema} TO "${targetRole}"`);
      await dbClient.query(`GRANT ALL ON ALL TABLES IN SCHEMA ${schema} TO "${targetRole}"`);
      await dbClient.query(
        `GRANT ALL ON ALL SEQUENCES IN SCHEMA ${schema} TO "${targetRole}"`,
      );
      await dbClient.query(
        `ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema} GRANT ALL ON TABLES TO "${targetRole}"`,
      );
    }
    console.log(`   ✅ privileges granted to '${targetRole}'`);
  } finally {
    await dbClient.end();
  }

  // -------------------------------------------------------------- verification
  // Connecting as the TEST role, not as admin: the proofs run as that role, so provisioning is
  // only complete if that role can actually write.
  const verify = new Client({ connectionString: targetUrl });
  await verify.connect();
  try {
    for (const table of REQUIRED_TABLES) {
      await verify.query(`SELECT 1 FROM env.${table.name} LIMIT 1`);
    }
    for (const name of RC6_OWNED_TABLES) {
      await verify.query(`SELECT 1 FROM env.${name} LIMIT 1`);
    }
    await verify.query(
      'INSERT INTO env.sgu_well (id, geom) VALUES (999999, ST_SetSRID(ST_MakePoint(0,0), 3006)) ' +
        'ON CONFLICT (id) DO NOTHING',
    );
    await verify.query('DELETE FROM env.sgu_well WHERE id = 999999');
    console.log('   ✅ test role can read, insert and delete\n');
    console.log('Provisioned. Run:  npx vitest run packages/spatial-provider-postgis\n');
  } finally {
    await verify.end();
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => fail(error instanceof Error ? error.message : String(error)));
}
