export const LocalOcrFailure = {
  EXECUTABLE_MISSING: "LOCAL_OCR_EXECUTABLE_MISSING",
  TIMEOUT: "LOCAL_OCR_TIMEOUT",
  NONZERO_EXIT: "LOCAL_OCR_NONZERO_EXIT",
  UNSUPPORTED_INPUT: "LOCAL_OCR_UNSUPPORTED_INPUT",
  UNSUPPORTED_LANGUAGE: "LOCAL_OCR_UNSUPPORTED_LANGUAGE",
  RENDERER_MISSING: "LOCAL_OCR_RENDERER_MISSING",
  RENDERER_FAILED: "LOCAL_OCR_RENDERER_FAILED",
  LANGUAGE_DATA_MISSING: "LOCAL_OCR_LANGUAGE_DATA_MISSING",
  LANGUAGE_DATA_HASH_MISMATCH: "LOCAL_OCR_LANGUAGE_DATA_HASH_MISMATCH",
  PAGE_LIMIT: "LOCAL_OCR_PAGE_LIMIT",
  OUTPUT_MISSING: "LOCAL_OCR_OUTPUT_MISSING",
  INPUT_TOO_LARGE: "LOCAL_OCR_INPUT_TOO_LARGE",
  SPAWN_ERROR: "LOCAL_OCR_SPAWN_ERROR",
  TEMP_CLEANUP_FAILED: "LOCAL_OCR_TEMP_CLEANUP_FAILED",
} as const;

export type LocalOcrFailureCode =
  (typeof LocalOcrFailure)[keyof typeof LocalOcrFailure];

export function failureNote(code: LocalOcrFailureCode, detail: string): string {
  const trimmed = detail.replace(/\s+/g, " ").trim();
  return trimmed.length > 0 ? `${code}: ${trimmed}` : code;
}
