export {
  KNOWLEDGE_INDEX_BUDGET_PROFILE,
  KNOWLEDGE_INDEX_PROJECTION_VERSION,
  KNOWLEDGE_SEARCH_VERSION,
} from './versions';
export {
  assertSameBinding,
  assertVectorBatchShape,
  bindingDigest,
  bindingOf,
  cosineSimilarity,
  createDeterministicHashEmbeddingProvider,
  describeBinding,
  EmbeddingProviderError,
  FIXTURE_HASH_EMBEDDING_DEFAULT_DIMENSIONS,
  FIXTURE_HASH_EMBEDDING_MODEL_ID,
  FIXTURE_HASH_EMBEDDING_MODEL_VERSION,
  FIXTURE_HASH_EMBEDDING_PIPELINE_VERSION,
  fitIdfTable,
  sameBinding,
  stemSwedish,
  tokenizeForFixtureEmbedding,
  type EmbeddingProviderBinding,
  type IdfTable,
  type KnowledgeEmbeddingProvider,
} from './EmbeddingProvider';
export {
  buildIndexProjection,
  chunkContentHash,
  computeIndexSnapshotIdentity,
  createGovernedKnowledgeLookup,
  currentDocumentIds,
  deserializeIndexProjection,
  expectedIndexRow,
  governedKey,
  verifyIndexProjectionWithReembedding,
  IndexProjectionError,
  isValidVector,
  rowDifferences,
  rowDigest,
  serializeIndexProjection,
  stripVector,
  vectorDigest,
  verifyIndexProjection,
  type GovernedEntry,
  type GovernedKnowledgeLookup,
  type IndexBuildStats,
  type IndexRow,
  type IndexRowMetadata,
  type IndexRowWithoutVector,
  type IndexViolation,
  type IndexViolationCode,
  type VerifyIndexOptions,
  type KnowledgeIndexProjection,
  type SkippedDocument,
} from './IndexProjection';
export {
  KnowledgeSearchError,
  matchesFilters,
  provenanceOfGoverned,
  provenanceRefsOf,
  queryHash,
  searchKnowledgeIndex,
  validateFilters,
  validateRequest,
  type KnowledgeRetrievalHit,
  type KnowledgeSearchOutcome,
  type KnowledgeSearchRequest,
  type ProvenanceResolution,
  type RetrievalFilters,
} from './IndexSearch';
