export type ArtifactType =
    | "PLAN"
    | "EVOLUTION_CANDIDATE"
    | "SHADOW_EVALUATION"
    | "PROMOTION_DECISION"
    | "GOVERNANCE_REVIEW"
    | "GOVERNANCE_APPROVAL"
    | "GOVERNANCE_POLICY"
    | "POLICY_SIMULATION"
    | "CAPABILITY_DEFINITION"
    | "CAPABILITY_EXECUTION"
    | "WORKFLOW_DEFINITION"
    | "WORKFLOW_EXECUTION"
    | "APPLICATION_ARTIFACT" | "APPLICATION_DEFINITION" | "CANONICAL_IMPLEMENTATION" | "APPLICATION_EXECUTION" | "AUDIT_ARTIFACT" | "AUDIT_CHAIN_ARTIFACT"
    | "CAPABILITY_REGISTRY_ENTRY"
    | "PROMOTION_CANDIDATE_ARTIFACT"
    | "PROMOTION_EVALUATION_ARTIFACT"
    | "PROMOTION_DECISION_ARTIFACT"
    | "PROMOTION_DECISION"
    | "ARTIFACT_LIFECYCLE_TRANSITION_ARTIFACT"
    | "REGISTRY_ENTRY"
    | "REGISTRY_MUTATION_REQUEST_ARTIFACT"
    | "REGISTRY_MUTATION_EXECUTION_ARTIFACT"
    | "REGISTRY_STATE_ARTIFACT"
    | "WORKFLOW_DEFINITION_ARTIFACT"
    | "WORKFLOW_EXECUTION_ARTIFACT"
    | "EVENT_ARTIFACT"
    | "EVENT_STREAM_ARTIFACT"
    | "GOVERNANCE_APPROVAL_ARTIFACT"
    | "GOVERNANCE_DECISION_ARTIFACT"
    | "POLICY_ARTIFACT"
    | "frozen_core_release_manifest"
    | "ARCHITECTURE_PROFILE_ARTIFACT"
    | "ARCHITECTURE_COMPLIANCE_ARTIFACT"
    | "AST_NORMALIZATION_PROFILE_ARTIFACT"
    | "DEPENDENCY_TAXONOMY_ARTIFACT"
    | "DEPENDENCY_ARTIFACT"
    | "SOURCE_REVISION_ARTIFACT"
    | "AST_SNAPSHOT_ARTIFACT"
    | "DEPENDENCY_ANALYSIS_ARTIFACT"
    | "DEPENDENCY_CONSTRAINT_ARTIFACT"
    | "DEPENDENCY_CONSTRAINT_PROFILE_ARTIFACT"
    | "DEPENDENCY_VIOLATION_ARTIFACT"
    | "DEPENDENCY_CONSTRAINT_EVALUATION_ARTIFACT" | "DEPENDENCY_ANALYSIS_PROFILE_ARTIFACT" | "PACKAGE_BOUNDARY_PROFILE_ARTIFACT";

export interface ContentReference {
    hash: string;
  artifact_id?: string;
    artifact_type: ArtifactType;
    schema_ref?: string;
}

export interface CanonicalArtifact {
    artifact_type: ArtifactType;
    content_hash: string;
  artifact_id?: string;
    schema_version: string;
    signature: ArtifactSignature;
}

export interface ArtifactSignature {
    algorithm: "SHA256";
    value: string;
}

export type Permission = string;
