export {
  CHUNK_POLICY_LAW_V241,
  CHUNK_POLICY_TEXT_V23,
  INGESTION_PIPELINE_VERSION,
  KNOWLEDGE_CORPUS_PROJECTION_VERSION,
  KNOWLEDGE_DOCUMENT_IDENTITY_VERSION,
  LINK_CANDIDATE_RULES_VERSION,
  SOURCE_ROLE_MAPPING_VERSION,
} from './versions';
export {
  classifySourceAuthority,
  createStaticAuthorizedSourceCatalog,
  SIGNED_REGISTRY_ORIGIN_PREFIX,
  STATIC_CATALOG_ORIGIN_PREFIX,
  type AuthorizedSourceBinding,
  type AuthorizedSourceCatalog,
  type SourceAuthorityOutcome,
} from './SourceAuthority';
export {
  buildKnowledgeDocumentIdentityPayload,
  buildRawSourceArtifactRef,
  computeKnowledgeDocumentId,
  sha256Hex,
  type KnowledgeDocumentIdentityInput,
} from './DocumentIdentity';
export {
  DOCUMENT_ROLES,
  evidenceDocTypeForRole,
  isDocumentRole,
  resolveDocumentRole,
  roleFromCallerDeclaration,
  roleFromClassifier,
  roleFromSourceDeclaration,
  structureKindForRole,
  type DocumentRole,
  type DocumentRoleAssignment,
  type RoleDerivationMethod,
} from './DocumentRole';
export {
  admitChunks,
  admitCourtChunks,
  admitEvidenceChunks,
  admitLawChunks,
  admitLawChunksV24,
  admitStandardChunks,
  type AdmissionDocumentStatus,
  type ChunkAdmissionResult,
  type RejectedFragment,
} from './ChunkAdmission';
export {
  admitWithPolicy,
  ChunkPolicyError,
  defaultChunkPolicyFor,
  registeredChunkPolicies,
} from './ChunkPolicyRegistry';
export {
  assertHtmlBytesWithinBudget,
  assertProjectedCharsWithinBudget,
  assertQuarantineId,
  assertRawBytesWithinBudget,
  ContentBudgetError,
  DEFAULT_CONTENT_BUDGET,
  PathEscapeError,
  resolveWithinRoot,
  type ContentBudget,
} from './PathSafety';
export {
  codepointCompare,
  deriveLinkCandidates,
  isAdmittedProjection,
  projectDocument,
  projectionFingerprint,
  type AcquisitionProvenance,
  type CorpusDocumentInput,
  type CorpusDocumentProjection,
  type LinkCandidate,
  type OcrPolicy,
  type ProjectDocumentOutcome,
  type ProjectionDependencies,
  type ProjectionStatus,
  type ProvenanceLink,
  type ProvenanceStage,
} from './CorpusProjection';
export {
  acquiredAtMs,
  buildCorpusSnapshot,
  CorpusSnapshotError,
  currencyByDocument,
  KNOWLEDGE_CORPUS_SNAPSHOT_VERSION,
  planIncrementalRebuild,
  verifyCorpusSnapshot,
  type CorpusSnapshot,
  type CurrencyMethod,
  type CurrencyReason,
  type DocumentCurrency,
  type DuplicateAcquisition,
  type IncrementalRebuildPlan,
  type RebuildPlanInput,
  type RelabeledMaterialization,
  type SnapshotVerificationViolation,
  type VersionLineage,
  type VersionMember,
} from './CorpusSnapshot';
