import { describe, expect, it } from 'vitest';
import { createDocumentEvidencePropertyBindingArtifactV3 } from '../src/artifacts/DocumentEvidencePropertyBindingArtifactV3';

const payload = () => ({ contract_version: 'document-evidence-property-binding-v3' as const, document_evidence_ref: { artifact_id: 'e', artifact_type: 'DOCUMENT_EVIDENCE', content_hash: 'a'.repeat(64) }, verified_fact_refs: [{ artifact_id: 'f', artifact_type: 'VERIFIED_DOCUMENT_FACT', content_hash: '9'.repeat(64) }], property_ref: { artifact_id: 'p', artifact_type: 'LU_PROPERTY_CONTEXT', content_hash: 'b'.repeat(64) }, binding_authority: { identity_ref: { id: 'r', content_hash: { algorithm: 'sha256', digest: 'c'.repeat(64) } }, role: 'GOVERNANCE_REVIEWER' as const }, justification_refs: [{ artifact_id: 'j', artifact_type: 'NOTE' }], review_attestation_ref: { artifact_id: 'a', artifact_type: 'DOCUMENT_PROPERTY_REVIEW_ATTESTATION' as const, content_hash: 'd'.repeat(64) } });
describe('DocumentEvidencePropertyBinding V3', () => {
  it('is deterministic and projects authority-bearing references exactly from its payload', () => { const p = payload(); const a = createDocumentEvidencePropertyBindingArtifactV3(p); const b = createDocumentEvidencePropertyBindingArtifactV3(p); expect(a).toEqual(b); expect(a.references).toEqual([{ artifact_id: p.document_evidence_ref.artifact_id, artifact_type: p.document_evidence_ref.artifact_type }, ...p.verified_fact_refs.map((ref) => ({ artifact_id: ref.artifact_id, artifact_type: ref.artifact_type })), { artifact_id: p.property_ref.artifact_id, artifact_type: p.property_ref.artifact_type }, ...p.justification_refs, { artifact_id: p.review_attestation_ref.artifact_id, artifact_type: p.review_attestation_ref.artifact_type }]); });
  it('denies the wrong review or property artifact type', () => { expect(() => createDocumentEvidencePropertyBindingArtifactV3({ ...payload(), review_attestation_ref: { ...payload().review_attestation_ref, artifact_type: 'OTHER' as never } })).toThrow(/DOCUMENT_PROPERTY_REVIEW_ATTESTATION/); expect(() => createDocumentEvidencePropertyBindingArtifactV3({ ...payload(), property_ref: { ...payload().property_ref, artifact_type: 'OTHER' } })).toThrow(/LU_PROPERTY_CONTEXT/); });
  it.each([
    ['review', (p: ReturnType<typeof payload>) => ({ ...p, review_attestation_ref: { ...p.review_attestation_ref, artifact_id: 'a2', content_hash: 'e'.repeat(64) } })],
    ['property', (p: ReturnType<typeof payload>) => ({ ...p, property_ref: { ...p.property_ref, artifact_id: 'p2', content_hash: 'f'.repeat(64) } })],
    ['justification', (p: ReturnType<typeof payload>) => ({ ...p, justification_refs: [{ artifact_id: 'j2', artifact_type: 'NOTE' }] })],
    ['evidence', (p: ReturnType<typeof payload>) => ({ ...p, document_evidence_ref: { ...p.document_evidence_ref, artifact_id: 'e2', content_hash: '1'.repeat(64) } })],
    ['verified fact', (p: ReturnType<typeof payload>) => ({ ...p, verified_fact_refs: [{ ...p.verified_fact_refs[0], artifact_id: 'f2', content_hash: '2'.repeat(64) }] })],
    ['authority', (p: ReturnType<typeof payload>) => ({ ...p, binding_authority: { ...p.binding_authority, identity_ref: { ...p.binding_authority.identity_ref, id: 'r2' } } })],
  ])('changes identity and hash when %s changes', (_, mutate) => { const a = createDocumentEvidencePropertyBindingArtifactV3(payload()); const b = createDocumentEvidencePropertyBindingArtifactV3(mutate(payload())); expect(b.artifact_id).not.toBe(a.artifact_id); expect(b.content_hash).not.toEqual(a.content_hash); });
  it('requires a review attestation reference', () => expect(() => createDocumentEvidencePropertyBindingArtifactV3({ ...payload(), review_attestation_ref: undefined as never })).toThrow(/review_attestation_ref is required/));
  it('requires verified fact references', () => expect(() => createDocumentEvidencePropertyBindingArtifactV3({ ...payload(), verified_fact_refs: [] })).toThrow(/verified_fact_refs/));
  it('requires a hash-bound governance reviewer authority', () => expect(() => createDocumentEvidencePropertyBindingArtifactV3({ ...payload(), binding_authority: { identity_ref: { id: 'r' }, role: 'HUMAN_OPERATOR' } as never })).toThrow(/hash-bound GOVERNANCE_REVIEWER/));
  it('treats justification_refs order as identity-bearing', () => { const p = payload(); const a = createDocumentEvidencePropertyBindingArtifactV3({ ...p, justification_refs: [{ artifact_id: 'j1', artifact_type: 'NOTE' }, { artifact_id: 'j2', artifact_type: 'NOTE' }] }); const b = createDocumentEvidencePropertyBindingArtifactV3({ ...p, justification_refs: [{ artifact_id: 'j2', artifact_type: 'NOTE' }, { artifact_id: 'j1', artifact_type: 'NOTE' }] }); expect(a.artifact_id).not.toBe(b.artifact_id); expect(a.content_hash).not.toEqual(b.content_hash); });
});
